spring:
    application:
        name: subjects
    datasource:
        url: jdbc:postgresql://localhost:5432/subjects
        driver-class-name: org.postgresql.Driver
        username: sa
        password: sa
        hikari:
            auto-commit: false
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        show-sql: false

    liquibase:
        default-schema: public

server:
    port: 8000

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka

users:
    service:
        url: http://localhost:8092/api/users/