spring:
    application:
        name: subjects
    datasource:
        url: jdbc:postgresql://localhost:5432/subjects
        driver-class-name: org.postgresql.Driver
        username: sa
        password: sa
        hikari:
            auto-commit: false
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        show-sql: false

    liquibase:
        default-schema: public

    kafka:
        bootstrapServers: "localhost:9092"

server:
    port: 0

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    instance:
        instance-id: ${spring.application.name}:${instanceId:${random.value}}

users:
    service:
        url: http://localhost:8092/api/users/

kafka:
    topic:
        courses-service:
            name: "courses-topic"
            groupId: "courses-group"
        subjects-service:
            name: "subjects-topic"
            groupId: "subjects-group"
        courses-subject-updated:
            name: "courses-subject-updated-topic"
            groupId: "courses-subject-updated-group"
