version: "3.8"

services:
  courses-mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo:/data/db

  courses-mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - courses-mongo
