version: "3.8"

services:
  users-postgresql:
    image: postgres:15.2
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=users
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/user-pg-data:/var/lib/postgresql/data
